[package]
name = "alpm"
version = "0.1.0"
authors = ["Richard Dodd <richard.dodd@itp-group.co.uk>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
fs2 = "0.4"
lockfile = "0.1"
log = "0.4"
reqwest = "0.8"
tempfile = "3"
